interface IUMS {
  Metric: Record<string, string | number>,
  Imperial: Record<string, string | number>,
  imp_to_metric: Record<string, string | number>,
  metric_to_imp: Record<string, string | number>
}
const UMS: IUMS = {
  "Metric": {
    "Allowance": "AL",
    "Analysis": "ANLS",
    "Apartment": "APT",
    "Assembly": "AMBY",
    "Bag": "BAG",
    "Bale": "BALE",
    "Bank Cubic Meter": "BCm",
    "Bar": "bar",
    "Barricade Day": "BDAY",
    "Block": "BLCK",
    "Bottle": "BOTTLE",
    "Box": "BOX",
    "Building": "BLDG",
    "Bundle": "BNDL",
    "Calculated": "CALC",
    "Calendar Day": "CDY",
    "Calendar Month": "CMO",
    "Calendar Week": "CWK",
    "Call": "CALL",
    "Centimeter": "cm",
    "Centimeter Diameter": "cmD",
    "Compact Volume": "CV",
    "Compacted Cubic Meter": "CCm",
    "Container Day": "CDAY",
    "Contingent Sum": "CTSM",
    "Cubic Centimeter": "cm3",
    "Cubic Decimeter": "dm3",
    "Cubic Dekameter": "dam3",
    "Cubic Meter": "m3",
    "Cubic Meter Kilometer": "m3km",
    "Cubic Meter Metric Station": "m3ST",
    "Cubic Meters per Hour": "m3HR",
    "Cubic Meters per Hundred Meters": "M3HM",
    "Cubic Meters per Second": "m3S",
    "Cut": "CUT",
    "Cycle": "CYC",
    "Decimeter": "dm",
    "Dekameter": "dam",
    "Dollar": "DLR",
    "Dollars Per Day": "$/DY",
    "Door": "DOOR",
    "Drum Day": "DDAY",
    "Each Day": "EADY",
    "Estimated Cost": "EST",
    "Fixed Quantity Unit": "FQU",
    "Force Account": "FA",
    "Gates": "GATE",
    "Gram": "g",
    "Gross Linear Kilometer": "GLkm",
    "Gross Linear Meter": "GLm",
    "Group": "GRP",
    "Hectare": "ha",
    "Hectoliter": "hL",
    "Horse Power Month": "HPMO",
    "Hundred": 100,
    "Hundred Pair": "CPR",
    "Hundred Square Meters": "C-m2",
    "Intersection": "INT",
    "Intersection Month": "INTM",
    "Inverter": "INV",
    "Inverter Skid (Power Control Unit)": "PCU",
    "Joint": "JT",
    "Joule": "J",
    "Junction Box": "JBOX",
    "Keg": "KEG",
    "Kilogram": "kg",
    "Kiloliter": "kL",
    "Kilometer": "km",
    "Kilometers Per Hour": "kph",
    "Kilonewton-Meter": "kNm",
    "Kilowatt": "kW",
    "Lane": "LN",
    "Lane Kilometer": "LNkm",
    "Light Day": "LDAY",
    "Linear Kilometer": "Lkm",
    "Linear Meter": "Lm",
    "Liter": "L",
    "Load": "LOAD",
    "Load Break Disconnect": "LBD",
    "Location": "LOC",
    "Loose Volume": "LV",
    "Lot": "LOT",
    "Luminaire": "LUM",
    "Man Day": "MDAY",
    "Man Hour": "MH",
    "Megagram": "Mg",
    "Megaliter": "Mltr",
    "MegaWatt": "MW",
    "MegaWatt dc": "MWdc",
    "Meter": "m",
    "Meter Day": "mDY",
    "Metric Station": "StaM",
    "Metric Station Meter": "Stm",
    "Metric Ton": "MT",
    "Milliliter": "ml",
    "Millimeter": "mm",
    "Millimeter-Meter": "mmm",
    "Million Volt Amperes": "MVA",
    "Minute": "MIN",
    "Module": "MOD",
    "Net Kilometer": "Nkm",
    "Night Unit": "NU",
    "Opening": "OPNG",
    "Pair": "PAIR",
    "Parcel": "PCL",
    "Pascal": "Pa",
    "Percent": "PCNT",
    "Piece": "PC",
    "Pile": "PILE",
    "Plant": "PLNT",
    "Plunge": "PLNG",
    "Pour": "POUR",
    "Predetermined Amount": "PDA",
    "Pressure Distributor Day": "PDD",
    "Provisional Sum": "PS",
    "Pull": "PULL",
    "Quality Unit": "QU",
    "Riser Meter": "Rm",
    "Roll": "ROLL",
    "Room": "ROOM",
    "Row": "ROW",
    "Sack": "SACK",
    "Set": "SET",
    "Sheet": "SHT",
    "Shoulder Kilometer": "SHkm",
    "Sign Day": "SDAY",
    "Sign Month": "SNMT",
    "Site": "SITE",
    "Slurry Units": "SLRY",
    "Span": "SPAN",
    "Square Centimeter": "cm2",
    "Square Kilometer": "km2",
    "Square Meter": "m2",
    "Square Meter Centimeter": "m2cm",
    "Square Meter Contact Area": "m2CA",
    "STEMS": "STEM",
    "String": "STRG",
    "Structure": "STR",
    "System": "SYS",
    "Thousand": 1000,
    "Thousand Square Meters": "Mm2",
    "Tonne": "TONN",
    "Tonne Kilometer": "TOkm",
    "Total": "TOTL",
    "Track Kilometer": "Tkm",
    "Track Meter": "Tm",
    "Tread": "TRED",
    "Tree": "TREE",
    "Trip": "TRIP",
    "Truck Load": "TL",
    "Unit Day": "UDAY",
    "Unit Price": "UP",
    "Unit Week": "UWK",
    "Unknown": "?",
    "Vertical Centimeter": "Vcm",
    "Vertical Meter": "Vm",
    "Vertical Millimeter": "Vmm",
    "Visit": "VST",
    "Watt": "W",
    "Watt dc": "Wdc",
    "Welding Inch": "WIN",
    "Well": "WELL",
    "Work Day": "WDAY",
    "Year": "YEAR"
  },
  "Imperial": {
    "Acre": "ACRE",
    "Allowance": "AL",
    "Analysis": "ANLS",
    "Apartment": "APT",
    "Assembly": "AMBY",
    "Bag": "BAG",
    "Bale": "BALE",
    "Bank Cubic Yard": "BCY",
    "Barrel [US, Liquid]": "BBL",
    "Barricade Day": "BDAY",
    "Block": "BLCK",
    "Board Foot": "BF",
    "Bottle": "BOTTLE",
    "Box": "BOX",
    "Building": "BLDG",
    "Bundle": "BNDL",
    "Calculated": "CALC",
    "Calendar Day": "CDY",
    "Calendar Month": "CMO",
    "Calendar Week": "CWK",
    "Call": "CALL",
    "Canadian Gallon": "CGAL",
    "Circuit Foot": "CKFT",
    "Circuit Mile": "CMI",
    "Compact Volume": "CV",
    "Compacted Cubic Yard": "CCY",
    "Container Day": "CDAY",
    "Contingent Sum": "CTSM",
    "Cubic Foot": "CF",
    "Cubic Inch": "CI",
    "Cubic Yard": "CY",
    "Cubic Yard Mile": "CYM",
    "Cubic Yard Station": "CYST",
    "Cubic Yard Trucked": "CYT",
    "Cubic Yards per Hour": "CYHR",
    "Cut": "CUT",
    "Cycle": "CYC",
    "Dollar": "DLR",
    "Dollars Per Day": "$/DY",
    "Door": "DOOR",
    "Drum [55 Gallon]": "DRUM",
    "Drum Day": "DDAY",
    "Each Day": "EADY",
    "Estimated Cost": "EST",
    "Face Foot": "FF",
    "Five Gallons": "5GAL",
    "Fixed Quantity Unit": "FQU",
    "Fluid Ounce [US]": "FLOZ",
    "Foot": "FOOT",
    "Foot Day": "FDAY",
    "Force Account": "FA",
    "Gallon": "GAL",
    "Gates": "GATE",
    "Gross Linear Foot": "GLF",
    "Gross Linear Mile": "GLMI",
    "Group": "GRP",
    "Horse Power Month": "HPMO",
    "Hundred": 100,
    "Hundred Cubic Feet": "CCF",
    "Hundred Feet": "100F",
    "Hundred Gallons": "HGAL",
    "Hundred Linear Feet": "CLF",
    "Hundred Pair": "CPR",
    "Hundred Square Feet": "CSF",
    "Hundred Square Yards": "CSY",
    "Hundredweight [Short]": "CWT",
    "Inch": "INCH",
    "Inch Diameter": "ID",
    "Inch-Foot": "INFT",
    "Inch-Yard": "INYD",
    "Intersection": "INT",
    "Intersection Month": "INTM",
    "Inverter": "INV",
    "Inverter Skid (Power Control Unit)": "PCU",
    "Joint": "JT",
    "Junction Box": "JBOX",
    "Keg": "KEG",
    "Kilowatt": "kW",
    "Kilowatt Hour": "KWH",
    "Lane": "LN",
    "Lane Mile": "LNMI",
    "Light Day": "LDAY",
    "Linear Foot": "LF",
    "Linear Mile": "LMI",
    "Load": "LOAD",
    "Load Break Disconnect": "LBD",
    "Location": "LOC",
    "Loose Cubic Yard": "LCY",
    "Loose Volume": "LV",
    "Lot": "LOT",
    "Luminaire": "LUM",
    "Man Day": "MDAY",
    "Man Hour": "MH",
    "MegaGallon": "MGGL",
    "MegaWatt": "MW",
    "MegaWatt dc": "MWdc",
    "Mile": "MILE",
    "Miles Per Hour": "MPH",
    "Million Volt Amperes": "MVA",
    "Minute": "MIN",
    "Module": "MOD",
    "Net Mile": "NMI",
    "Night Unit": "NU",
    "Opening": "OPNG",
    "Ounce": "OZ",
    "Pair": "PAIR",
    "Parcel": "PCL",
    "Per Mile Per Side": "PMPS",
    "Percent": "PCNT",
    "Piece": "PC",
    "Pile": "PILE",
    "Pint": "PT",
    "Plant": "PLNT",
    "Plunge": "PLNG",
    "Pound": "LB",
    "Pound Force Foot (Foot Pound)": "LBF",
    "Pound per Square Inch": "PSI",
    "Pour": "POUR",
    "Predetermined Amount": "PDA",
    "Pressure Distributor Day": "PDD",
    "Provisional Sum": "PS",
    "Pull": "PULL",
    "Quality Unit": "QU",
    "Quart": "QT",
    "Riser Foot": "RF",
    "Roll": "ROLL",
    "Room": "ROOM",
    "Row": "ROW",
    "Sack": "SACK",
    "Set": "SET",
    "Sheet": "SHT",
    "Short Ton": "STON",
    "Shoulder Mile": "SHMI",
    "Sign Day": "SDAY",
    "Sign Month": "SNMT",
    "Site": "SITE",
    "Slurry Units": "SLRY",
    "Span": "SPAN",
    "Square": "SQR",
    "Square Foot": "SF",
    "Square Foot Contact Area": "SFCA",
    "Square Foot Inch": "SFI",
    "Square Inch": "SI",
    "Square Mile": "SM",
    "Square Yard": "SY",
    "Square Yard Inch": "SYIN",
    "Station": "ST",
    "Station Yard": "STY",
    "Statute Mile": "SMI",
    "STEMS": "STEM",
    "String": "STRG",
    "Structure": "STR",
    "System": "SYS",
    "Thousand": 1000,
    "Thousand Board Feet": "MBM",
    "Thousand Cubic Feet": "MCF",
    "Thousand Cubic Feet per Minute": "MCFM",
    "Thousand Gallons": "MGAL",
    "Thousand Linear Feet": "MLF",
    "Thousand Pounds": "KIP",
    "Thousand Square Feet": "MSF",
    "Thousand Square Yards": "MSY",
    "Three Gallons": "3GAL",
    "Ton": "TON",
    "Ton Mile": "TONM",
    "Total": "TOTL",
    "Tote": "TOTE",
    "Track Foot": "TF",
    "Track Mile": "TMI",
    "Track Yard": "TY",
    "Tread": "TRED",
    "Tree": "TREE",
    "Trench Foot": "TRFT",
    "Trip": "TRIP",
    "Truck Load": "TL",
    "Unit Day": "UDAY",
    "Unit Price": "UP",
    "Unit Week": "UWK",
    "Unknown": "?",
    "Vertical Foot": "VF",
    "Vertical Inch": "VI",
    "Vertical Linear Foot": "VLF",
    "Vertical Square Foot": "VSF",
    "Visit": "VST",
    "Watt": "W",
    "Watt dc": "Wdc",
    "Welding Inch": "WIN",
    "Well": "WELL",
    "Work Day": "WDAY",
    "Yard": "YARD",
    "Year": "YEAR"
  },
  "imp_to_metric": {
    "Acre": "Hectare",
    "Bank Cubic Yard": "Bank Cubic Meter",
    "Barrel [US, Liquid]": "Liter",
    "Board Foot": "Cubic Meter",
    "Canadian Gallon": "Liter",
    "Circuit Foot": "Meter",
    "Circuit Mile": "Kilometer",
    "Compacted Cubic Yard": "Compacted Cubic Meter",
    "Cubic Foot": "Cubic Meter",
    "Cubic Inch": "Cubic Centimeter",
    "Cubic Yard": "Cubic Meter",
    "Cubic Yard Mile": "Cubic Meter Kilometer",
    "Cubic Yard Station": "Cubic Meter Metric Station",
    "Cubic Yard Trucked": "Cubic Meter",
    "Cubic Yards per Hour": "Cubic Meters per Hour",
    "Drum [55 Gallon]": "Liter",
    "Face Foot": "Square Meter",
    "Five Gallons": "Liter",
    "Fluid Ounce [US]": "Cubic Centimeter",
    "Foot": "Meter",
    "Foot Day": "Meter Day",
    "Gallon": "Liter",
    "Gross Linear Foot": "Gross Linear Meter",
    "Gross Linear Mile": "Gross Linear Kilometer",
    "Hundred Cubic Feet": "Cubic Meter",
    "Hundred Feet": "Meter",
    "Hundred Gallons": "Liter",
    "Hundred Linear Feet": "Meter",
    "Hundred Square Feet": "Hundred Square Meters",
    "Hundred Square Yards": "Hundred Square Meters",
    "Hundredweight [Short]": "Kilogram",
    "Inch": "Centimeter",
    "Inch Diameter": "Centimeter Diameter",
    "Inch-Foot": "Millimeter-Meter",
    "Inch-Yard": "Millimeter-Meter",
    "Kilowatt Hour": "Kilonewton-Meter",
    "Lane Mile": "Lane Kilometer",
    "Linear Foot": "Meter",
    "Linear Mile": "Kilometer",
    "Loose Cubic Yard": "Cubic Meter",
    "MegaGallon": "Cubic Meter",
    "Mile": "Kilometer",
    "Miles Per Hour": "Kilometers Per Hour",
    "Net Mile": "Net Kilometer",
    "Ounce": "Gram",
    "Per Mile Per Side": "Kilometer",
    "Pint": "Liter",
    "Pound": "Kilogram",
    "Pound Force Foot (Foot Pound)": "Kilonewton-Meter",
    "Pound per Square Inch": "Pascal",
    "Quart": "Liter",
    "Riser Foot": "Riser Meter",
    "Short Ton": "Metric Ton",
    "Shoulder Mile": "Shoulder Kilometer",
    "Square": "Square Meter",
    "Square Foot": "Square Meter",
    "Square Foot Contact Area": "Square Meter Contact Area",
    "Square Foot Inch": "Cubic Meter",
    "Square Inch": "Square Centimeter",
    "Square Mile": "Square Kilometer",
    "Square Yard": "Square Meter",
    "Square Yard Inch": "Square Meter Centimeter",
    "Station": "Metric Station",
    "Station Yard": "Metric Station Meter",
    "Statute Mile": "Kilometer",
    "Thousand Board Feet": "Cubic Meter",
    "Thousand Cubic Feet": "Cubic Meter",
    "Thousand Cubic Feet per Minute": "Cubic Meters per Hour",
    "Thousand Gallons": "Kiloliter",
    "Thousand Linear Feet": "Meter",
    "Thousand Pounds": "Megagram",
    "Thousand Square Feet": "Hundred Square Meters",
    "Thousand Square Yards": "Thousand Square Meters",
    "Three Gallons": "Liter",
    "Ton": "Metric Ton",
    "Ton Mile": "Tonne Kilometer",
    "Tote": "Liter",
    "Track Foot": "Track Meter",
    "Track Mile": "Track Kilometer",
    "Track Yard": "Track Meter",
    "Trench Foot": "Meter",
    "Vertical Foot": "Vertical Meter",
    "Vertical Inch": "Vertical Meter",
    "Vertical Linear Foot": "Vertical Meter",
    "Vertical Square Foot": "Square Meter",
    "Yard": "Meter"
  },
  "metric_to_imp": {
    "Bank Cubic Meter": "Bank Cubic Yard",
    "Bar": "Pound per Square Inch",
    "Centimeter": "Inch",
    "Centimeter Diameter": "Inch Diameter",
    "Compacted Cubic Meter": "Compacted Cubic Yard",
    "Cubic Centimeter": "Fluid Ounce [US]",
    "Cubic Decimeter": "Gallon",
    "Cubic Dekameter": "Cubic Yard",
    "Cubic Meter": "Cubic Yard",
    "Cubic Meter Kilometer": "Cubic Yard Mile",
    "Cubic Meter Metric Station": "Cubic Yard Station",
    "Cubic Meters per Hour": "Cubic Yards per Hour",
    "Cubic Meters per Hundred Meters": "Cubic Yard Mile",
    "Cubic Meters per Second": "Thousand Cubic Feet per Minute",
    "Decimeter": "Foot",
    "Dekameter": "Yard",
    "Gram": "Ounce",
    "Gross Linear Kilometer": "Gross Linear Mile",
    "Gross Linear Meter": "Gross Linear Foot",
    "Hectare": "Acre",
    "Hectoliter": "Gallon",
    "Hundred Square Meters": "Hundred Square Yards",
    "Joule": "Kilowatt Hour",
    "Kilogram": "Ton",
    "Kiloliter": "Thousand Gallons",
    "Kilometer": "Mile",
    "Kilometers Per Hour": "Miles Per Hour",
    "Kilonewton-Meter": "Pound Force Foot (Foot Pound)",
    "Lane Kilometer": "Lane Mile",
    "Linear Kilometer": "Linear Mile",
    "Linear Meter": "Linear Foot",
    "Liter": "Gallon",
    "Megagram": "Ton",
    "Megaliter": "Thousand Gallons",
    "Meter": "Linear Foot",
    "Meter Day": "Foot Day",
    "Metric Station": "Station",
    "Metric Station Meter": "Station Yard",
    "Metric Ton": "Ton",
    "Milliliter": "Fluid Ounce [US]",
    "Millimeter": "Inch",
    "Millimeter-Meter": "Inch-Yard",
    "Net Kilometer": "Net Mile",
    "Pascal": "Pound per Square Inch",
    "Riser Meter": "Riser Foot",
    "Shoulder Kilometer": "Shoulder Mile",
    "Square Centimeter": "Square Inch",
    "Square Kilometer": "Square Mile",
    "Square Meter": "Square Yard",
    "Square Meter Centimeter": "Square Yard Inch",
    "Square Meter Contact Area": "Square Foot Contact Area",
    "Thousand Square Meters": "Thousand Square Yards",
    "Tonne": "Ton",
    "Tonne Kilometer": "Ton Mile",
    "Track Kilometer": "Track Mile",
    "Track Meter": "Track Yard",
    "Vertical Centimeter": "Inch",
    "Vertical Meter": "Vertical Foot",
    "Vertical Millimeter": "Inch"
  }
}